spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          # git远程仓库url
          uri: https://github.com/yzw88/config-demo/
          # git仓库文件夹
          search-paths: config
          username:
          password:
      # 分支名称
      label: master

server:
  port: 8700
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8288/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
