spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          # git远程仓库url
          uri: https://github.com/yzw88/config-demo/
          # git仓库文件夹
          search-paths: config
          username:
          password:
      # 分支名称
      label: master
#服务端不用开启
#    bus:
#      trace:
#        enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
server:
  port: 8700
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8288/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
